import rpyc
import numpy as np
import matplotlib.pyplot as plt

samples = 4096

c = rpyc.connect("192.168.7.2", 18861)

c.root.pru_communicate("10000")

data = c.root.pru_read(samples)

sin_array = np.asarray(data)

sin_array -= 32767

samp_freq = 10000  # Hz
freq = 100  # Hz
sample = len(sin_array)
x = np.arange(samples)


Aosin = 32767 * np.sin(2 * np.pi * freq * x / samp_freq)
Aosinturn = np.int16(32767 * np.sin(2 * np.pi * freq * x / samp_freq))

plt.subplot(2, 1, 1)
plt.title("SIN generated by Python")
plt.plot(x[:samples], Aosin[:samples])
plt.subplot(2, 1, 2)
plt.title("SIN generated by beaglebone")
plt.plot(x[:samples], sin_array[:samples])
plt.tight_layout()
plt.show()

plt.title("FFT of SIN generated by Python")
plt.magnitude_spectrum(Aosin[:samples], Fs=samp_freq, scale='dB', color='C1')
plt.xscale("log")
plt.xlim(0, 5000)
plt.ylim(-100, 100)
plt.grid()
plt.show()

plt.title("FFT of SIN generated by Python (16-bit)")
plt.magnitude_spectrum(Aosinturn[:samples], Fs=samp_freq, scale='dB', color='C1')
plt.xscale("log")
plt.xlim(0, 5000)
plt.ylim(-100, 100)
plt.grid()
plt.show()

plt.title("FFT of SIN generated by BeagleBone Black 16 bit, 256 sample LUT")
plt.magnitude_spectrum(sin_array[:samples], Fs=samp_freq, scale='dB', color='C2')
plt.xscale("log")
plt.xlim(0, 5000)
plt.ylim(-100, 100)
plt.grid()
plt.show()

c.close()
